### ISSUE TITLE
pylint fails for pytest modules

### ISSUE THREAD

**Issue by amendlik** [saltstack/salt-pylint#45]
Running `pylint` on any module in `tests/pytests/unit/modules` produces a stack trace:
```
Traceback (most recent call last):
  File "/home/amendlik/.local/bin/pylint", line 10, in <module>
    sys.exit(run_pylint())
  File "/home/amendlik/.local/lib/python3.7/site-packages/pylint/__init__.py", line 24, in run_pylint
    PylintRun(sys.argv[1:])
  File "/home/amendlik/.local/lib/python3.7/site-packages/pylint/lint/run.py", line 358, in __init__
    linter.check(args)
  File "/home/amendlik/.local/lib/python3.7/site-packages/pylint/lint/pylinter.py", line 877, in check
    self.get_ast, self._iterate_file_descrs(files_or_modules)
  File "/home/amendlik/.local/lib/python3.7/site-packages/pylint/lint/pylinter.py", line 910, in _check_files
    self._check_file(get_ast, check_astroid_module, name, filepath, modname)
  File "/home/amendlik/.local/lib/python3.7/site-packages/pylint/lint/pylinter.py", line 936, in _check_file
    check_astroid_module(ast_node)
  File "/home/amendlik/.local/lib/python3.7/site-packages/pylint/lint/pylinter.py", line 1071, in check_astroid_module
    ast_node, walker, rawcheckers, tokencheckers
  File "/home/amendlik/.local/lib/python3.7/site-packages/pylint/lint/pylinter.py", line 1115, in _check_astroid_module
    walker.walk(ast_node)
  File "/home/amendlik/.local/lib/python3.7/site-packages/pylint/utils/ast_walker.py", line 75, in walk
    self.walk(child)
  File "/home/amendlik/.local/lib/python3.7/site-packages/pylint/utils/ast_walker.py", line 72, in walk
    callback(astroid)
  File "/home/amendlik/.local/lib/python3.7/site-packages/saltpylint/thirdparty.py", line 123, in visit_import
    self._check_third_party_import(node, name)
  File "/home/amendlik/.local/lib/python3.7/site-packages/saltpylint/thirdparty.py", line 135, in _check_third_party_import
    if is_relative(modname, module_file):
  File "/home/amendlik/.local/lib/python3.7/site-packages/astroid/modutils.py", line 581, in is_relative
    parent_spec = importlib.util.find_spec(name, from_file)
  File "/usr/lib/python3.7/importlib/util.py", line 94, in find_spec
    parent = __import__(parent_name, fromlist=['__path__'])
ModuleNotFoundError: No module named 'pytests'
```

**Comment by s0undt3ch** [comment]
I don't have a clue on why you're getting that...

```bash
❯ git reset --hard upstream/master
HEAD is now at 5457218d86 change pypi-proxy url
~/projects/SaltStack/salt/branches/master (master↑6|…)
❯ virtualenv /tmp/.venv
created virtual environment CPython3.6.8.final.0-64 in 206ms
  creator CPython3Posix(dest=/tmp/.venv, clear=False, no_vcs_ignore=False, global=False)
  seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=/home/vampas/.local/share/virtualenv)
    added seed packages: pip==21.0.1, setuptools==56.0.0, wheel==0.36.2
  activators BashActivator,CShellActivator,FishActivator,PowerShellActivator,PythonActivator,XonshActivator
~/projects/SaltStack/salt/branches/master (master↑6|…) __VIRTUAL_ENV__
❯ source /tmp/.venv/bin/activate.fish
~/projects/SaltStack/salt/branches/master (master↑6|…) .venv
❯ pip install -r requirements/static/ci/py3.6/lint.txt
Collecting astroid==2.3.3
  Using cached astroid-2.3.3-py3-none-any.whl (205 kB)
Collecting isort==4.3.17
  Using cached isort-4.3.17-py2.py3-none-any.whl (42 kB)
Collecting lazy-object-proxy==1.4.3
  Using cached lazy_object_proxy-1.4.3-cp36-cp36m-manylinux1_x86_64.whl (55 kB)
Collecting mccabe==0.6.1
  Using cached mccabe-0.6.1-py2.py3-none-any.whl (8.6 kB)
Collecting modernize==0.5
  Using cached modernize-0.5-py3-none-any.whl
Collecting pycodestyle==2.5.0
  Using cached pycodestyle-2.5.0-py2.py3-none-any.whl (51 kB)
Collecting pylint==2.4.4
  Using cached pylint-2.4.4-py3-none-any.whl (302 kB)
Collecting saltpylint==2020.9.28
  Using cached SaltPyLint-2020.9.28-py2.py3-none-any.whl (38 kB)
Collecting six==1.15.0
  Using cached six-1.15.0-py2.py3-none-any.whl (10 kB)
Collecting toml==0.10.2
  Using cached toml-0.10.2-py2.py3-none-any.whl (16 kB)
Collecting typed-ast==1.4.1
  Using cached typed_ast-1.4.1-cp36-cp36m-manylinux1_x86_64.whl (737 kB)
Collecting wrapt==1.11.1
  Using cached wrapt-1.11.1-cp36-cp36m-linux_x86_64.whl
Installing collected packages: wrapt, typed-ast, six, lazy-object-proxy, mccabe, isort, astroid, pylint, pycodestyle, modernize, toml, saltpylint
Successfully installed astroid-2.3.3 isort-4.3.17 lazy-object-proxy-1.4.3 mccabe-0.6.1 modernize-0.5 pycodestyle-2.5.0 pylint-2.4.4 saltpylint-2020.9.28 six-1.15.0 toml-0.10.2 typed-ast-1.4.1 wrapt-1.11.1
WARNING: You are using pip version 21.0.1; however, version 21.1.2 is available.
You should consider upgrading via the '/tmp/.venv/bin/python -m pip install --upgrade pip' command.
~/projects/SaltStack/salt/branches/master (master↑6|…) .venv
❯ pylint tests/pytests/unit/modules/test_alternatives.py

------------------------------------
Your code has been rated at 10.00/10
```
* What OS are you on?
* Which python version?
* How did you install pylint and it's dependencies?

Also, linting salt should be done using nox, `nox -e lint-salt` or `nox -e lint-tests`

**Comment by amendlik** [comment]
It's working fine for me after following your procedure. I had no idea I had to install all those dependencies to make `pylint` work. That may be an opportunity to clarify the documentation.

Nox is fine for running tests, but many text editors have built-in support for external linters like `pylint`. I use Sublime and really like the highlights that appear right in the editor for linter problems. I think this is something Salt should continue to support.

**Comment by sagetherage** [comment]
closing this as the docs clarification will be in the Silicon release cycle and the Silicon release date is still TBD, but will be in 2021 for sure.
