### ISSUE TITLE
pylint 2.17.4 crash after SaltPyLint is installed

### ISSUE THREAD

**Issue by MaxBear** [saltstack/salt-pylint#47]
When running `pylint --rcfile=.pylintrc salt//.py` in pipenv environment, with 
```
pipenv run pylint --version
pylint 2.13.9
astroid 2.11.7
Python 3.9.16 (main, Dec  7 2022, 10:06:04)
[Clang 14.0.0 (clang-1400.0.29.202)]
```
and 
```
SaltPyLint = "==2020.9.28"
```
Everything work fine. But when running pylint with following versions after SaltPyLint is installed, pylint will crash 
```
pylint --version
pylint 2.17.4
astroid 2.15.5
Python 3.11.3 (main, Apr  7 2023, 20:13:31) [Clang 14.0.0 (clang-1400.0.29.202)]
```
or with 
```
pylint --version
pylint 2.17.4
astroid 2.15.5
Python 3.9.16 (main, Dec  7 2022, 10:06:04)
[Clang 14.0.0 (clang-1400.0.29.202)]
```
The traceback is 
```
Traceback (most recent call last):
  File "/opt/homebrew/bin/pylint", line 8, in <module>
    sys.exit(run_pylint())
  File "/opt/homebrew/lib/python3.9/site-packages/pylint/__init__.py", line 36, in run_pylint
    PylintRun(argv or sys.argv[1:])
  File "/opt/homebrew/lib/python3.9/site-packages/pylint/lint/run.py", line 169, in __init__
    args = _config_initialization(
  File "/opt/homebrew/lib/python3.9/site-packages/pylint/config/config_initialization.py", line 54, in _config_initialization
    linter.load_plugin_modules(utils._splitstrip(config_data["load-plugins"]))
  File "/opt/homebrew/lib/python3.9/site-packages/pylint/lint/pylinter.py", line 384, in load_plugin_modules
    module.register(self)
  File "/opt/homebrew/lib/python3.9/site-packages/saltpylint/py3modernize/__init__.py", line 247, in register
    linter.register_checker(Py3Modernize(linter))
  File "/opt/homebrew/lib/python3.9/site-packages/saltpylint/checkers.py", line 20, in __init__
    super(BaseChecker, self).__init__(*args, **kwargs)
  File "/opt/homebrew/lib/python3.9/site-packages/pylint/checkers/base_checker.py", line 62, in __init__
    _ArgumentsProvider.__init__(self, linter)
  File "/opt/homebrew/lib/python3.9/site-packages/pylint/config/arguments_provider.py", line 48, in __init__
    self._arguments_manager._register_options_provider(self)
  File "/opt/homebrew/lib/python3.9/site-packages/pylint/config/arguments_manager.py", line 145, in _register_options_provider
    argument = _convert_option_to_argument(opt, optdict)
  File "/opt/homebrew/lib/python3.9/site-packages/pylint/config/utils.py", line 138, in _convert_option_to_argument
    return _StoreArgument(
  File "/opt/homebrew/lib/python3.9/site-packages/pylint/config/argument.py", line 261, in __init__
    self.type = _TYPE_TRANSFORMERS[arg_type]
KeyError: 'multiple_choice'
```

**Comment by s0undt3ch** [comment]
Python 2 is no longer supported

**Comment by mirceaulinic** [comment]
@s0undt3ch fyi, the above is not on Python 2. 😄

**Comment by s0undt3ch** [comment]
Woops.

**Comment by s0undt3ch** [comment]
This should be fixed now
